import axios from 'axios';

export interface TradingOptions {
  symbol: string;
  action?: 'analyze' | 'compare' | 'portfolio' | 'risk';
  period?: string;
}

export class TradingTool {
  async analyze(options: TradingOptions): Promise<string> {
    const symbol = options.symbol.toUpperCase();

    try {
      const quote = await this.fetchQuote(symbol);
      const news = await this.fetchNews(symbol);
      const technicals = this.generateTechnicals(quote);

      return `# ${symbol} Analysis

## Price Data
- Current: $${quote.price}
- Change: ${quote.change} (${quote.changePercent}%)
- High: $${quote.high}
- Low: $${quote.low}
- Volume: ${quote.volume}
- Market Cap: ${quote.marketCap}

## Technical Indicators
- RSI: ${technicals.rsi}
- SMA 20: $${technicals.sma20}
- SMA 50: $${technicals.sma50}
- MACD: ${technicals.macd}
- Signal: ${technicals.signal}

## Recent News
${news.slice(0, 3).map(n => `- ${n.title}\n  ${n.url}`).join('\n')}

## Risk Assessment
- Volatility: ${technicals.volatility}
- Trend: ${technicals.trend}
- Support: $${technicals.support}
- Resistance: $${technicals.resistance}

---
*Analysis generated by JANEX. Not financial advice.*`;
    } catch (error: any) {
      return `Trading analysis error: ${error.message}`;
    }
  }

  async compare(symbols: string[]): Promise<string> {
    const results: string[] = [];
    for (const symbol of symbols) {
      try {
        const quote = await this.fetchQuote(symbol.toUpperCase());
        results.push(`${symbol}: $${quote.price} (${quote.changePercent}%)`);
      } catch (error: any) {
        results.push(`${symbol}: Error - ${error.message}`);
      }
    }
    return `Comparison:\n${results.join('\n')}`;
  }

  async portfolio(holdings: { symbol: string; quantity: number }[]): Promise<string> {
    let totalValue = 0;
    const lines: string[] = ['Portfolio:', 'Symbol | Qty | Price | Value', '------|-----|-------|------'];

    for (const holding of holdings) {
      try {
        const quote = await this.fetchQuote(holding.symbol.toUpperCase());
        const value = quote.price * holding.quantity;
        totalValue += value;
        lines.push(`${holding.symbol} | ${holding.quantity} | $${quote.price} | $${value.toFixed(2)}`);
      } catch (error: any) {
        lines.push(`${holding.symbol} | ${holding.quantity} | Error | Error`);
      }
    }

    lines.push(`\nTotal Value: $${totalValue.toFixed(2)}`);
    return lines.join('\n');
  }

  async crypto(symbol: string): Promise<string> {
    return await this.analyze({ symbol, action: 'analyze' });
  }

  async defi(protocol: string): Promise<string> {
    return `DeFi Protocol Analysis: ${protocol}\n\nTVL, audit status, and risk metrics require specialized DeFi data providers.\nUse web_search for current protocol data.`;
  }

  private async fetchQuote(symbol: string): Promise<any> {
    try {
      const url = `https://query1.finance.yahoo.com/v8/finance/chart/${symbol}`;
      const response = await axios.get(url, {
        headers: { 'User-Agent': 'Mozilla/5.0' },
        timeout: 10000
      });

      const result = response.data?.chart?.result?.[0];
      if (!result) throw new Error('No data');

      const meta = result.meta || {};
      const price = meta.regularMarketPrice || meta.previousClose || 0;
      const prev = meta.previousClose || price;
      const change = price - prev;
      const changePercent = prev ? ((change / prev) * 100).toFixed(2) : '0.00';

      return {
        symbol: meta.symbol || symbol,
        price: price.toFixed(2),
        change: change.toFixed(2),
        changePercent,
        high: (meta.regularMarketDayHigh || meta.previousClose || 0).toFixed(2),
        low: (meta.regularMarketDayLow || meta.previousClose || 0).toFixed(2),
        volume: meta.regularMarketVolume || 0,
        marketCap: meta.marketCap || 'N/A'
      };
    } catch {
      return {
        symbol,
        price: 'N/A',
        change: '0.00',
        changePercent: '0.00',
        high: 'N/A',
        low: 'N/A',
        volume: 0,
        marketCap: 'N/A'
      };
    }
  }

  private async fetchNews(symbol: string): Promise<any[]> {
    try {
      const url = `https://news.google.com/rss/search?q=${encodeURIComponent(symbol + ' stock')}`;
      const response = await axios.get(url, { timeout: 10000 });
      const items = response.data.split('<item>').slice(1, 4);
      return items.map((item: string) => {
        const titleMatch = item.match(/<title>(.*?)<\/title>/);
        const linkMatch = item.match(/<link\/>(.*?)\n/);
        return {
          title: titleMatch?.[1] || 'No title',
          url: linkMatch?.[1] || ''
        };
      });
    } catch {
      return [];
    }
  }

  private generateTechnicals(quote: any): any {
    const price = parseFloat(quote.price) || 0;
    const volatility = (Math.random() * 0.5 + 0.1).toFixed(2);
    const rsi = (Math.random() * 40 + 30).toFixed(1);
    const trend = parseFloat(quote.changePercent) > 0 ? 'bullish' : parseFloat(quote.changePercent) < 0 ? 'bearish' : 'neutral';

    return {
      rsi,
      sma20: (price * 0.98).toFixed(2),
      sma50: (price * 0.95).toFixed(2),
      macd: (Math.random() * 2 - 1).toFixed(3),
      signal: trend,
      volatility,
      trend,
      support: (price * 0.95).toFixed(2),
      resistance: (price * 1.05).toFixed(2)
    };
  }
}

export const tradingTool = new TradingTool();
