import { execFile } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import type { Tool } from './Registry.js';

const SKILL_DIR = path.resolve(import.meta.dirname, '../../skills/research/social-researching');
const ENGINE = path.join(SKILL_DIR, 'scripts', 'social-researching.py');

function shellSafeName(input: string): string {
  return (
    input
      .replace(/[^a-zA-Z0-9一-鿿]+/g, '_')
      .replace(/^_+|_+$/g, '')
      .slice(0, 70) || 'china_ai'
  );
}

function parseSources(raw: unknown): string {
  const value = typeof raw === 'string' ? raw.trim() : '';
  return value || 'nodeloc,xiaohongshu,grounding,hackernews,github,youtube';
}

function buildChinaAIPlan(query: string, sources: string[]) {
  const enabled = new Set(sources.map((s) => s.trim()).filter(Boolean));
  const pick = (...preferred: string[]) => preferred.filter((s) => enabled.has(s));
  const all = sources.filter(Boolean);
  const fallback = all.length ? all : ['nodeloc'];
  const sourceOrFallback = (...preferred: string[]) => {
    const chosen = pick(...preferred);
    return chosen.length ? chosen : fallback;
  };

  return {
    intent: 'breaking_news',
    freshness_mode: 'strict_recent',
    cluster_mode: 'story',
    source_weights: {
      nodeloc: 1.25,
      xiaohongshu: 1.15,
      grounding: 1.0,
      hackernews: 0.8,
      github: 0.75,
      youtube: 0.7,
    },
    subqueries: [
      {
        label: 'china-ai-news',
        search_query: `${query} 中国 AI 大模型 最新 DeepSeek Kimi 豆包 通义千问`,
        ranking_query:
          'What are the newest China AI model, product, policy, infrastructure, and developer ecosystem updates?',
        sources: sourceOrFallback('nodeloc', 'grounding', 'xiaohongshu', 'hackernews'),
        weight: 1.25,
      },
      {
        label: 'developer-community-sentiment',
        search_query: `${query} nodeloc 中国 AI 大模型 开发者 讨论 吐槽 评价`,
        ranking_query:
          'What are Chinese developers and technical communities saying about China AI products, APIs, prices, quality, and adoption?',
        sources: sourceOrFallback('nodeloc', 'xiaohongshu', 'github'),
        weight: 1.2,
      },
      {
        label: 'infrastructure-cost-chips',
        search_query: `${query} 中国 AI 算力 GPU 推理 成本 国产芯片`,
        ranking_query:
          'What are the strongest signals about China AI compute, chips, inference cost, infrastructure, and deployment constraints?',
        sources: sourceOrFallback('nodeloc', 'grounding', 'github', 'hackernews'),
        weight: 0.95,
      },
      {
        label: 'product-adoption-complaints',
        search_query: `${query} 国产 AI 用户 体验 好用 难用 吐槽 评价`,
        ranking_query:
          'What do users say about practical adoption, complaints, strengths, and weaknesses of Chinese AI tools?',
        sources: sourceOrFallback('nodeloc', 'xiaohongshu', 'youtube', 'grounding'),
        weight: 0.9,
      },
    ],
    notes: ['Generated by janex china_ai_research for China AI social/news crawling.'],
  };
}

export const chinaAIResearchTool: Tool = {
  name: 'china_ai_research',
  description:
    'China AI social/news research: crawls NodeLoc plus available China/social/web sources to find latest China AI news and what Chinese communities are saying. Public read-only crawling; no paid API required for NodeLoc.',
  parameters: {
    type: 'object',
    properties: {
      query: {
        type: 'string',
        description: 'Topic to research (default: AI in China / 中国 AI 大模型)',
      },
      days: {
        type: 'number',
        description: 'Lookback window in days (default: 30)',
      },
      sources: {
        type: 'string',
        description:
          'Comma-separated sources (default: nodeloc,xiaohongshu,grounding,hackernews,github,youtube). Sources gracefully skip when unavailable.',
      },
      format: {
        type: 'string',
        description: 'Output format: compact, json, html (default: compact)',
      },
      limit: {
        type: 'number',
        description: 'Max results per source (default: 12)',
      },
    },
    required: [],
  },
  async execute(args) {
    if (!fs.existsSync(ENGINE)) {
      return `Error: China AI research engine not found at ${ENGINE}. Skill not installed correctly.`;
    }

    const query = String(args.query || 'AI in China / 中国 AI 大模型').trim();
    const days = Math.max(1, Math.min(365, Number(args.days || 30)));
    const limit = Math.max(1, Math.min(50, Number(args.limit || 12)));
    const formatRaw = String(args.format || 'compact').toLowerCase();
    const format = ['compact', 'json', 'html'].includes(formatRaw) ? formatRaw : 'compact';
    const sources = parseSources(args.sources)
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);

    const outputDir = path.join(os.homedir(), '.janex', 'research', 'china-ai');
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const planPath = path.join(os.tmpdir(), `janex-china-ai-plan-${Date.now()}.json`);
    fs.writeFileSync(planPath, JSON.stringify(buildChinaAIPlan(query, sources), null, 2), 'utf-8');

    const childArgs = [
      ENGINE,
      query,
      `--emit=${format}`,
      `--limit=${limit}`,
      `--days=${days}`,
      `--search=${sources.join(',')}`,
      `--plan=${planPath}`,
      `--save-dir=${outputDir}`,
      '--save-suffix=china-ai',
    ];

    return new Promise<string>((resolve) => {
      execFile(
        'python3',
        childArgs,
        {
          timeout: 180000,
          maxBuffer: 15 * 1024 * 1024,
          cwd: SKILL_DIR,
          env: {
            ...process.env,
            SKILL_DIR,
            PYTHONPATH: path.join(SKILL_DIR, 'scripts'),
            INCLUDE_SOURCES: process.env.INCLUDE_SOURCES || sources.join(','),
          },
        },
        (err, stdout, stderr) => {
          try {
            fs.unlinkSync(planPath);
          } catch {}
          const out = stdout.trim();
          const errText = (stderr || err?.message || '').trim();
          const filename = `${shellSafeName(query)}-${Date.now()}.${format === 'json' ? 'json' : format === 'html' ? 'html' : 'md'}`;
          const outputFile = path.join(outputDir, filename);

          if (out) {
            try {
              fs.writeFileSync(outputFile, out, 'utf-8');
            } catch {}
          }

          if (err && !out) {
            resolve(
              `China AI research failed: ${errText.slice(0, 1000) || err.message}\n\n` +
                `Try narrower sources first: sources=nodeloc or sources=nodeloc,grounding.\n` +
                `NodeLoc is public/keyless; Xiaohongshu requires the optional local XHS service.`
            );
            return;
          }

          const warnings = errText
            .split('\n')
            .filter((line) => /warning|failed|unavailable|error/i.test(line))
            .slice(0, 8)
            .join('\n');

          resolve(
            `${out || '(no output)'}\n\n---\n` +
              `🇨🇳 China AI research sources: ${sources.join(', ')}\n` +
              `📅 Lookback: ${days} day(s)\n` +
              `💾 Saved: ${outputFile}` +
              (warnings ? `\n⚠️ Notes:\n${warnings}` : '')
          );
        }
      );
    });
  },
};

